package cmd

import (
	"fmt"
)

func PrintUsage() {
	fmt.Println("Redway - Redroid Container Manager")
	fmt.Println("\nUsage: redway [command] [options]")
	fmt.Println("\nCommands:")
	fmt.Println("  prepare-lxc                    Prepare LXC system (one-time setup)")
	fmt.Println("  unprepare-lxc                  Clean up LXC system (reverses prepare-lxc)")
	fmt.Println("  init <name> [image]            Initialize container (name required)")
	fmt.Println("  start <name>                   Start container (name required)")
	fmt.Println("  stop <name>                    Stop container (name required)")
	fmt.Println("  restart <name>                 Restart container (name required)")
	fmt.Println("  status <name>                  Show container status (name required)")
	fmt.Println("  shell <name>                   Enter container shell (name required)")
	fmt.Println("  adb-connect <name>             Show ADB connection command (name required)")
	fmt.Println("  remove <name>                  Remove container and data (name required)")
	fmt.Println("  list                           List all Redway containers")
	fmt.Println("  log <name>                     Show container logs (name required)")
	fmt.Println("\nExamples:")
	fmt.Println("  # First time setup:")
	fmt.Println("  sudo redway prepare-lxc")
	fmt.Println("  sudo redway init android16")
	fmt.Println("  sudo redway start android16")
	fmt.Println("")
	fmt.Println("  # Custom image:")
	fmt.Println("  sudo redway init android15 docker://redroid/redroid:15.0.0_64only-latest")
	fmt.Println("  sudo redway start android15")
	fmt.Println("")
	fmt.Println("  # Multiple containers:")
	fmt.Println("  sudo redway init pixel docker://redroid/redroid:16.0.0_64only-latest")
	fmt.Println("  sudo redway init samsung docker://redroid/redroid:15.0.0_64only-latest")
	fmt.Println("  sudo redway start pixel")
	fmt.Println("  sudo redway start samsung")
	fmt.Println("  redway list")
	fmt.Println("")
	fmt.Println("  # Container management:")
	fmt.Println("  redway status pixel")
	fmt.Println("  redway adb-connect pixel")
	fmt.Println("  redway shell samsung")
	fmt.Println("  redway log pixel")
	fmt.Println("  sudo redway stop samsung")
	fmt.Println("  sudo redway restart pixel")
	fmt.Println("  sudo redway remove samsung")
	fmt.Println("")
	fmt.Println("  # Cleanup:")
	fmt.Println("  sudo redway remove pixel")
	fmt.Println("  sudo redway remove samsung")
	fmt.Println("  sudo redway unprepare-lxc")
	fmt.Println("\nDefault image: docker://redroid/redroid:16.0.0_64only-latest")
	fmt.Println("\nNote: Container name is now REQUIRED for all commands.")
	fmt.Println("      Container paths: /var/lib/lxc/<container-name>/")
	fmt.Println("      Data paths: ~/data-<container-name>/")
}
