#!/usr/bin/env bash
# Writes appimagecraft.yml in the repo root (appimagecraft only reads that path).
# Shared by Makefile and .github/workflows/release.yml — keep AppImage settings in one place.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/appimagecraft.yml"
cat >"$OUT" <<'EOF'
# Generated by packaging/write-appimagecraft-yml.sh — do not edit appimagecraft.yml by hand.
version: 1

project:
  name: io.github.reddock.reddock
  version_command: 'cd "$PROJECT_ROOT" && printf "%s-%s" "$(git rev-list --count HEAD 2>/dev/null || echo 0)" "$(date +%d%m%y)"'

build:
  null:

scripts:
  post_build:
    - |
      set -eux
      test -x "$PROJECT_ROOT/reddock"
      cp -a "$PROJECT_ROOT/reddock" "$BUILD_DIR/reddock"
      # linuxdeploy needs a real icon file (theme names are not resolved at bundle time).
      echo 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==' | base64 -d >"$BUILD_DIR/reddock.png"

appimage:
  linuxdeploy:
    extra_args: -i "$BUILD_DIR"/reddock.png -d "$PROJECT_ROOT"/packaging/appimage/reddock.desktop -e "$BUILD_DIR"/reddock
    raw_environment:
      - OUTPUT=reddock-x86_64.AppImage
EOF
